# Prompt user to choose whether to save output to a file
$saveToFile = Read-Host "Do you want to save the output to a file? (yes/no)"

# Define the list of services to check
$services = @(
    @{ FullName = "ActiveX Installer"; ShortName = "AxInstSV" },
    @{ FullName = "AllJoyn Router Service"; ShortName = "AJRouter" },
    @{ FullName = "App Readiness"; ShortName = "AppReadiness" },
    @{ FullName = "Application Identity"; ShortName = "AppIDSvc" },
    @{ FullName = "Application Information"; ShortName = "Appinfo" },
    @{ FullName = "Application Layer Gateway Service"; ShortName = "ALG" },
    @{ FullName = "Application Management"; ShortName = "AppMgmt" },
    @{ FullName = "AppX Deployment Service"; ShortName = "AppXSVC" },
    @{ FullName = "Auto Time Zone Updater"; ShortName = "AutoTimeZoneUpdater" },
    @{ FullName = "AVCTP service"; ShortName = "BthAvctpSvc" },
    @{ FullName = "Background Intelligent Transfer Service"; ShortName = "BITS" },
    @{ FullName = "Background Tasks Infrastructure Service"; ShortName = "BrokerInfrastructure" },
    @{ FullName = "Base Filtering Engine"; ShortName = "BFE" },
    @{ FullName = "Bluetooth Audio Gateway Service"; ShortName = "BTAGService" },
    @{ FullName = "Bluetooth Support Service"; ShortName = "bthserv" },
    @{ FullName = "Capability Access Manager Service"; ShortName = "camsvc" },
    @{ FullName = "CaptureService"; ShortName = "CaptureService" },
    @{ FullName = "Certificate Propagation"; ShortName = "CertPropSvc" },
    @{ FullName = "Client License Service"; ShortName = "ClipSVC" },
    @{ FullName = "Clipboard User Service"; ShortName = "cbdhsvc" },
    @{ FullName = "CNG Key Isolation"; ShortName = "KeyIso" },
    @{ FullName = "COM+ Event System"; ShortName = "EventSystem" },
    @{ FullName = "COM+ System Application"; ShortName = "COMSysApp" },
    @{ FullName = "Computer Browser"; ShortName = "Browser" },
    @{ FullName = "Connected Devices Platform Service"; ShortName = "CDPSvc" },
    @{ FullName = "Connected Devices Platform User Service"; ShortName = "CDPUserSvc" },
    @{ FullName = "Connected User Experiences and Telemetry"; ShortName = "DiagTrack" },
    @{ FullName = "ConsentUX"; ShortName = "ConsentUxUserSvc" },
    @{ FullName = "Contact Data"; ShortName = "PimIndexMaintenanceSvc" },
    @{ FullName = "CoreMessaging"; ShortName = "CoreMessagingRegistrar" },
    @{ FullName = "Credential Manager"; ShortName = "VaultSvc" },
    @{ FullName = "Cryptographic Services"; ShortName = "CryptSvc" },
    @{ FullName = "Data Sharing Service"; ShortName = "DsSvc" },
    @{ FullName = "DCOM Server Process Launcher"; ShortName = "DcomLaunch" },
    @{ FullName = "Delivery Optimization"; ShortName = "DoSvc" },
    @{ FullName = "Device Association Service"; ShortName = "DeviceAssociationService" },
    @{ FullName = "Device Install Service"; ShortName = "DeviceInstall" },
    @{ FullName = "Device Management Enrollment Service"; ShortName = "DmEnrollmentSvc" },
    @{ FullName = "Device Management Wireless Application Protocol (WAP) Push message Routing Service"; ShortName = "dmwappushservice" },
    @{ FullName = "Device Setup Manager"; ShortName = "DsmSvc" },
    @{ FullName = "DevicePicker"; ShortName = "DevicePickerUserSvc" },
    @{ FullName = "DevicesFlow"; ShortName = "DevicesFlowUserSvc" },
    @{ FullName = "DevQuery Background Discovery Broker"; ShortName = "DevQueryBroker" },
    @{ FullName = "DHCP Client"; ShortName = "Dhcp" },
    @{ FullName = "Diagnostic Policy Service"; ShortName = "DPS" },
    @{ FullName = "Diagnostic Service Host"; ShortName = "WdiServiceHost" },
    @{ FullName = "Diagnostic System Host"; ShortName = "WdiSystemHost" },
    @{ FullName = "Distributed Link Tracking Client"; ShortName = "TrkWks" },
    @{ FullName = "Distributed Transaction Coordinator"; ShortName = "MSDTC" },
    @{ FullName = "DNS Client"; ShortName = "Dnscache" },
    @{ FullName = "Downloaded Maps Manager"; ShortName = "MapsBroker" },
    @{ FullName = "Embedded Mode"; ShortName = "EmbeddedMode" },
    @{ FullName = "Encrypting File System (EFS)"; ShortName = "EFS" },
    @{ FullName = "Enterprise App Management Service"; ShortName = "EntAppSvc" },
    @{ FullName = "Extensible Authentication Protocol"; ShortName = "Eaphost" },
    @{ FullName = "Function Discovery Provider host"; ShortName = "FDPhost" },
    @{ FullName = "Function Discovery Resource Publication"; ShortName = "FDResPub" },
    @{ FullName = "Geolocation Service"; ShortName = "lfsvc" },
    @{ FullName = "GraphicsPerfSvc"; ShortName = "GraphicsPerfSvc" },
    @{ FullName = "Group Policy Client"; ShortName = "gpsvc" },
    @{ FullName = "Human Interface Device Access"; ShortName = "hidserv" },
    @{ FullName = "HV Host Service"; ShortName = "HvHost" },
    @{ FullName = "Hyper-V Data Exchange Service"; ShortName = "vmickvpexchange" },
    @{ FullName = "Hyper-V Guest Service Interface"; ShortName = "vmicguestinterface" },
    @{ FullName = "Hyper-V Guest Shutdown Service"; ShortName = "vmicshutdown" },
    @{ FullName = "Hyper-V Heartbeat Service"; ShortName = "vmicheartbeat" },
    @{ FullName = "Hyper-V PowerShell Direct Service"; ShortName = "vmicvmsession" },
    @{ FullName = "Hyper-V Remote Desktop Virtualization Service"; ShortName = "vmicrdv" },
    @{ FullName = "Hyper-V Time Synchronization Service"; ShortName = "vmictimesync" },
    @{ FullName = "Hyper-V Volume Shadow Copy Requestor"; ShortName = "vmicvss" },
    @{ FullName = "IKE and AuthIP IPsec Keying Modules"; ShortName = "IKEEXT" },
    @{ FullName = "Internet Connection Sharing (ICS)"; ShortName = "SharedAccess" },
    @{ FullName = "IP Helper"; ShortName = "iphlpsvc" },
    @{ FullName = "IPSec Policy Agent (IPSec Service)"; ShortName = "PolicyAgent" },
    @{ FullName = "KDC Proxy Server service (KPS)"; ShortName = "KPS" },
    @{ FullName = "KtmRm for Distributed Transaction Coordinator"; ShortName = "KtmRm" },
    @{ FullName = "Link-Layer Topology Discovery Mapper"; ShortName = "lltdsvc" },
    @{ FullName = "Local Session Manager"; ShortName = "lsm" },
    @{ FullName = "Microsoft (R) Diagnostics Hub Standard Collector Service"; ShortName = "DiagSvcs" },
    @{ FullName = "Microsoft Account Sign-in Assistant"; ShortName = "wlidsvc" },
    @{ FullName = "Microsoft App-V Client"; ShortName = "AppVClient" },
    @{ FullName = "Microsoft iSCSI Initiator Service"; ShortName = "MSiSCSI" },
    @{ FullName = "Microsoft Passport"; ShortName = "NgcSvc" },
    @{ FullName = "Microsoft Passport Container"; ShortName = "NgcCtnrSvc" },
    @{ FullName = "MS Software Shadow Copy Provider"; ShortName = "swprv" },
    @{ FullName = "Microsoft Storage Spaces SMP"; ShortName = "SpacePort" },
    @{ FullName = "Microsoft Store Install Service"; ShortName = "InstallService" },
    @{ FullName = "Net.Tcp Port Sharing Service"; ShortName = "NetTcpPortSharing" },
    @{ FullName = "Netlogon"; ShortName = "Netlogon" },
    @{ FullName = "Network Connection Broker"; ShortName = "NcbService" },
    @{ FullName = "Network Connections"; ShortName = "Netman" },
    @{ FullName = "Network Connectivity Assistant"; ShortName = "NcaSvc" },
    @{ FullName = "Network List Service"; ShortName = "NlaSvc" },
    @{ FullName = "Network Location Awareness (NLA)"; ShortName = "NetSetupSvc" },
    @{ FullName = "Network Store Interface Service"; ShortName = "nsi" },
    @{ FullName = "Offline Files"; ShortName = "CscService" },
    @{ FullName = "OpenSSH Authentication Agent"; ShortName = "ssh-agent" },
    @{ FullName = "Optimize drives"; ShortName = "defragsvc" },
    @{ FullName = "Payments and NFC/SE Manager"; ShortName = "NfcSvc" },
    @{ FullName = "Performance Counter DLL Host"; ShortName = "PerfHost" },
    @{ FullName = "Performance Logs and Alerts"; ShortName = "pla" },
    @{ FullName = "Phone Service"; ShortName = "PhoneSvc" },
    @{ FullName = "Plug and Play"; ShortName = "PlugPlay" },
    @{ FullName = "Portable Device Enumerator Service"; ShortName = "WPDBusEnum" },
    @{ FullName = "Power"; ShortName = "power" },
    @{ FullName = "Print Spooler"; ShortName = "Spooler" },
    @{ FullName = "Printer Extensions and Notifications"; ShortName = "PrintNotify" },
    @{ FullName = "PrintWorkflow"; ShortName = "PrintWorkflowUserSvc" },
    @{ FullName = "Problem Reports and Solutions Control Panel Support"; ShortName = "wercplsupport" },
    @{ FullName = "Program Compatibility Assistant Service"; ShortName = "PcaSvc" },
    @{ FullName = "Quality Windows Audio Video Experience"; ShortName = "QWAVE" },
    @{ FullName = "Radio Management Service"; ShortName = "RadioMgr" },
    @{ FullName = "Remote Access Auto Connection Manager"; ShortName = "RasAuto" },
    @{ FullName = "Remote Access Connection Manager"; ShortName = "RasMan" },
    @{ FullName = "Remote Desktop Configuration"; ShortName = "SessionEnv" },
    @{ FullName = "Remote Desktop Services"; ShortName = "TermService" },
    @{ FullName = "Remote Desktop Services UserMode Port Redirector"; ShortName = "UmRdpService" },
    @{ FullName = "Remote Procedure Call (RPC)"; ShortName = "RpcSs" },
    @{ FullName = "Remote Procedure Call (RPC) Locator"; ShortName = "RpcLocator" },
    @{ FullName = "Remote Registry"; ShortName = "RemoteRegistry" },
    @{ FullName = "Resultant Set of Policy Provider"; ShortName = "RSoPProv" },
    @{ FullName = "Routing and Remote Access"; ShortName = "RemoteAccess" },
    @{ FullName = "RPC Endpoint Mapper"; ShortName = "RpcEptMapper" },
    @{ FullName = "Secondary Logon"; ShortName = "seclogon" },
    @{ FullName = "Secure Socket Tunneling Protocol Service"; ShortName = "SstpSvc" },
    @{ FullName = "Security Accounts Manager"; ShortName = "SamSs" },
    @{ FullName = "Sensor Data Service"; ShortName = "SensorDataService" },
    @{ FullName = "Sensor Monitoring Service"; ShortName = "SensrSvc" },
    @{ FullName = "Sensor Service"; ShortName = "SensorService" },
    @{ FullName = "Server"; ShortName = "LanmanServer" },
    @{ FullName = "Shared PC Account Manager"; ShortName = "shpamsvc" },
    @{ FullName = "Shell Hardware Detection"; ShortName = "ShellHWDetection" },
    @{ FullName = "Smart Card"; ShortName = "SCardSvr" },
    @{ FullName = "Smart Card Device Enumeration Service"; ShortName = "ScDeviceEnum" },
    @{ FullName = "Smart Card Removal Policy"; ShortName = "SCPolicySvc" },
    @{ FullName = "SNMP Trap"; ShortName = "SNMPTRAP" },
    @{ FullName = "Software Protection"; ShortName = "sppsvc" },
    @{ FullName = "Special Administration Console Helper"; ShortName = "sacsvr" },
    @{ FullName = "Spot Verifier"; ShortName = "sppsvc" },
    @{ FullName = "SSDP Discovery"; ShortName = "SSDPSRV" },
    @{ FullName = "State Repository Service"; ShortName = "StateRepository" },
    @{ FullName = "Still Image Acquisition Events"; ShortName = "WiaRpc" },
    @{ FullName = "Storage Service"; ShortName = "StorSvc" },
    @{ FullName = "Storage Tiers Management"; ShortName = "TieringEngineService" },
    @{ FullName = "SysMain"; ShortName = "SysMain" },
    @{ FullName = "System Event Notification Service"; ShortName = "SENS" },
    @{ FullName = "System Events Broker"; ShortName = "SystemEventsBroker" },
    @{ FullName = "System Guard Runtime Monitor Broker"; ShortName = "SgrmBroker" },
    @{ FullName = "Task Scheduler"; ShortName = "Schedule" },
    @{ FullName = "TCP/IP NetBIOS Helper"; ShortName = "lmhosts" },
    @{ FullName = "Telephony"; ShortName = "TapiSrv" },
    @{ FullName = "Themes"; ShortName = "Themes" },
    @{ FullName = "Time Broker"; ShortName = "TimeBrokerSvc" },
    @{ FullName = "Touch Keyboard and Handwriting Panel Service"; ShortName = "TabletInputService" },
    @{ FullName = "Update Orchestrator Service"; ShortName = "UsoSvc" },
    @{ FullName = "UPnP Device Host"; ShortName = "upnphost" },
    @{ FullName = "User Access Logging Service"; ShortName = "UALSVC" },
    @{ FullName = "User Data Access"; ShortName = "UserDataSvc" },
    @{ FullName = "User Data Storage"; ShortName = "UnistoreSvc" },
    @{ FullName = "User Experience Virtualization Service"; ShortName = "UEVAgentService" },
    @{ FullName = "User Manager"; ShortName = "UserManager" },
    @{ FullName = "User Profile Service"; ShortName = "ProfSvc" },
    @{ FullName = "Virtual Disk"; ShortName = "vds" },
    @{ FullName = "Volume Shadow Copy"; ShortName = "VSS" },
    @{ FullName = "WalletService"; ShortName = "WalletService" },
    @{ FullName = "WarpJITSvc"; ShortName = "WarpJITSvc" },
    @{ FullName = "Web Account Manager"; ShortName = "TokenBroker" },
    @{ FullName = "Windows Audio"; ShortName = "Audiosrv" },
    @{ FullName = "Windows Audio Endpoint Builder"; ShortName = "AudioEndpointBuilder" },
    @{ FullName = "Windows Biometric Service"; ShortName = "WbioSrvc" },
    @{ FullName = "Windows Camera Frame Server"; ShortName = "FrameServer" },
    @{ FullName = "Windows Connection Manager"; ShortName = "Wcmsvc" },
    @{ FullName = "Windows Defender Advanced Threat Protection Service"; ShortName = "Sense" },
    @{ FullName = "Windows Defender Firewall"; ShortName = "MpsSvc" },
    @{ FullName = "Windows Encryption Provider Host Service"; ShortName = "WEPHostSvc" },
    @{ FullName = "Windows Error Reporting Service"; ShortName = "WerSvc" },
    @{ FullName = "Windows Event Collector"; ShortName = "Wecsvc" },
    @{ FullName = "Windows Event Log"; ShortName = "EventLog" },
    @{ FullName = "Windows Font Cache Service"; ShortName = "FontCache" },
    @{ FullName = "Windows Image Acquisition (WIA)"; ShortName = "stisvc" },
    @{ FullName = "Windows Insider Service"; ShortName = "wisvc" },
    @{ FullName = "Windows Installer"; ShortName = "msiserver" },
    @{ FullName = "Windows License Manager Service"; ShortName = "LicenseManager" },
    @{ FullName = "Windows Management Instrumentation"; ShortName = "Winmgmt" },
    @{ FullName = "Windows Media Player Network Sharing Service"; ShortName = "WMPNetworkSvc" },
    @{ FullName = "Windows Mobile Hotspot Service"; ShortName = "icssvc" },
    @{ FullName = "Windows Modules Installer"; ShortName = "TrustedInstaller" },
    @{ FullName = "Windows Presentation Foundation Font Cache 3.0.0.0"; ShortName = "FontCache3.0.0.0" },
    @{ FullName = "Windows Push Notifications System Service"; ShortName = "WpnService" },
    @{ FullName = "Windows Push Notifications User Service"; ShortName = "WpnUserService" },
    @{ FullName = "Windows PushToInstall Service"; ShortName = "PushToInstall" },
    @{ FullName = "Windows Remote Management (WS-Management)"; ShortName = "WinRM" },
    @{ FullName = "Windows Search"; ShortName = "WSearch" },
    @{ FullName = "Windows Security Service"; ShortName = "SecurityHealthService" },
    @{ FullName = "Windows Time"; ShortName = "W32Time" },
    @{ FullName = "Windows Update"; ShortName = "wuauserv" },
    @{ FullName = "Windows Update Medic Service"; ShortName = "WaaSMedicSvc" },
    @{ FullName = "WinHTTP Web Proxy Auto-Discovery Service"; ShortName = "WinHttpAutoProxySvc" },
    @{ FullName = "Wired AutoConfig"; ShortName = "dot3svc" },
    @{ FullName = "WMI Performance Adapter"; ShortName = "wmiApSrv" },
    @{ FullName = "Workstation"; ShortName = "LanmanWorkstation" },
    @{ FullName = "Dell SecureWorks Ignition"; ShortName = "SecureWorksIgnition" },
    @{ FullName = "Dell SecureWorks Red Cloak"; ShortName = "SecureWorksRedCloak" },
    @{ FullName = "nxlog"; ShortName = "nxlog" },
    @{ FullName = "ForeScout Remote Inspection Service"; ShortName = "ForeScoutRemoteInspection" },
    @{ FullName = "Microsoft Monitoring Agent"; ShortName = "HealthService" },
    @{ FullName = "Microsoft Monitoring Agent Audit Forwarding"; ShortName = "AuditForwardingService" },
    @{ FullName = "Symantec Endpoint Protection"; ShortName = "SepMasterService" },
    @{ FullName = "Symantec Endpoint Protection Local Proxy Service"; ShortName = "ccSvcHst" },
    @{ FullName = "Symantec Endpoint Protection Scan Service"; ShortName = "ccScan" },
    @{ FullName = "Symantec Endpoint Protection WSC Service"; ShortName = "WSCService" },
    @{ FullName = "Symantec Network Access Control"; ShortName = "SNAC" }
)

# Function to check the status of a service
function Get-ServiceStatus($serviceName) {
    $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
    if ($service) {
        switch ($service.StartType) {
            "Automatic" { return "Automatic" }
            "Manual" { return "Manual" }
            "Disabled" { return "Disabled" }
            default { return "Unknown" }
        }
    } else {
        return "Not Found"
    }
}

# Array to hold the output lines
$outputLines = @()

# Check each service and add the result to the output array
foreach ($service in $services) {
    $status = Get-ServiceStatus -serviceName $service.ShortName
    $outputLines += "$($service.FullName) $($service.ShortName) $status"
}

# Output to file or console based on user's choice
if ($saveToFile -eq "yes") {
    $outputFile = "Windows Server 2019 Services Hardening Checklist.txt"
    $outputLines | Out-File -FilePath $outputFile
    Write-Host "Output saved to $outputFile"
} else {
    $outputLines | ForEach-Object { Write-Host $_ }
}
